#------------------------------------------------------------------------
# Source File Information (DO NOT MODIFY)
# Source ID: 640ec93d-ac9e-4251-9ecc-86fa0ef6d530
# Source File: CToolbox GUI.psf
#------------------------------------------------------------------------
#region File Recovery Data (DO NOT MODIFY)
<#RecoveryData:
czoAAB+LCAAAAAAABADtW2tv4joT/o7Ef4j42qohXFqQWiQHQsue0uXW65ejENxslpCgXBror3/H
cUJCSMDptmh79O5KZcexZ56ZeTx2ZsvlCCvmG7bWHdmROfiHrZnGValyJpRaxQLHXf60NFUzZL2r
6fhOXuBWe2Ka+tRccdf3vbOl/XrJ70yhC6e/seJwznqJr0rjte3gxdmjZsxMzz7rmtaC/jzl0h6d
cg8BktpZmfw95dqu7rgWvjKw61iyfsoN3KmuKf/g9cScY+NqenEh15X6udCs1nC50SxxBkC5Kr2C
vhByiVN+afrMgumltmk4lqnb1E3AO7DMJbacdbAOuY45VmQdd7QFNggWmHp+ygnVSz6cemhp35zh
UqsLlg6uaesaNpyx9g4LKrXaKVepVQ4u6sua0ceGO3YsbRk6AtNG+BWDkwoO5oEDrk3mCCWOD3Ud
Vr7SFoBHhLi1urJu44NLSPJLrXjEDy6Z4JVTamVPl94gLMHcW1Oebav/lwxd8v6kcMVh3t3KU6x/
OfEczdGxTkzto10Kewzll2mVWhNzecqJpuOYi52wZHDOZ8/Ecncztbvg1lRkBxwttargZLXOsISm
N/KLYQmFVBdg31wwTJ/I054xw0A4gQUQJc8j1hVzweIzmY90TQWn+9pspuM28AZbDCvvbdw2F0uI
2FTHRM0IA05LM9SMgENV9HnIzkrRhVQbX18PXUMhea/lY2VEF6FSP+UaTWa+bAwy06UJ7lV2y+w+
urDAoWzJAyd31lNVPGi2K+tjZ61jUVbmbVP3tzfbelhMjGdV4ESFhFNEmcd8/NcfSBTIv52Z1Y8y
s9L8EDFZmPZhYjZyE5NF/3cnZvVbErPyRyXzvJybmbs3wE9kJtN5vMVMFjjfnZmVb8lM4U9K5geI
KXwlMc9zE5MFzncnpvA5xNy8Ln45N+MvnXnI2QNQsccwgYzs84m8DPo+EefI5K/zLQYr5T0b3JQH
uum0f2FlvoMqevemqSNj39LNKTDfXY6w7ZgWzudmrhdTQM5emiK6MdemoM+S772UuTjtAfTXnicr
3V6JFmjGXVOH6vjRY+WCVP0yS2Rp8pJ2mVMolOu5zxemhPsppJC4E05aLU1rt4n33zllkgn4nMOG
BEA0V0eh7dRcfYSzpG9GMqZjJ2jXjl1VhdKGlktIHWPnLdQwNl1LIaHXdEx97mgWBMm0NGznqn11
uJhVBPbytxUC5u1TvSD7NNfuYdlrByiYn0jH6dj6TU261Uk48xPpgw1YckcWGuzVMoGTOdvn1fxt
WKbS6hdLCog7Y4T0CZXy+9NMsd+OxzKS/SpLP2qHZQCTnWTl/CRjaSxsk4wN0d/IsSPd5CBAn3WR
E+rspEmY/f897sj3uET8v9c1DsD/x25xQi3fLS4eAfZLXPN7XOJGmvLrWFRaWqaCbTCxciCgf9Qe
FZg6BDR/CbPs5a9BfrOkzNT5jI5N9gKYo/2SJ+3bwmEG9Bayim812/ny/GvEkg6W6HEruvYaGTBI
0xq4kmw8kjVjx8LyIhYxUTNka91CSEIIdXjyBw1R+KePVPjZnU3w01355bHsPlR09+W6WVXW9etp
9YejrD31YfGwVir62/R3uXz7G7nFQr9d827bYmf2uCrPnn7og8e6PnsarZ8fPbvXFYXnxWr5XHZ0
/DB6kysP7uCxV72rSMLz+32lP5m/313fez878y5BUiyg9sse+/Uf08eu8XK/WirV0WR280N/fhR0
RSX+IGl03S0/D5W27wead0Ab8dPrw0+x0iajc2EyMobieNgFbyWxTSIxQSIs9sC+KBF5ROQJj8YS
fP7m0X1PnAylSrEgeki8U0HbWO1AoBACuQ9hQ0MyU1JFFeRBA/Feh0cHPgEb/MtVAZ56w6P3msh7
/RP02vDlPgrGBTL+sx2O2zA+IONgmSd+wTiRIQvwRE1oegJZRekWehmaUKMnFgu8d4fJiBqM8CuI
HfkMNIQzw3mDjQVfhiD+HJPxuY/Nn1kFDRSDbwuhYMU6SzP1OtLsy0OSUzrT10DRb7xKxgvVI01q
KMeQgLY4lnd4ItS2sRB5lYGdjFMLvrfFwjxEX83w6j0cPxzfIG6bJ1FEqSb1gAXq9VOU082TQXtb
0zA+Xs6Ir4dQlGvAFmXbC7Pte1PbYIXxQZSJyIKXtED4FtpIzfpGkxrlNNOCn9PNk0jTYFeTsDs+
31ig0SB8i2xI4W7yMzNMjXQsA+NknIOc+rqb9xnxGcYjnRnnOt2n+yLdHGZYiMlUo0dzWkvwicjr
LXZIrJkg2Ha9hDJJ41GL4jaPsGzHcR3xle7TpBfJXMUtvYSW6tuZIHWyWEiLhx3mtr4dl7t4zi+G
O3soyOnWLjop59sTJ2o4Xiw8bVYkvYwwiak8TOzrrLjN4xhmKeeGmmDHPJHTNMameivFLf2IY97C
psCTpxQMUmJFfBcmo0Jrbz9jhbJ1ntLdReRu+n4eU2zpFbJpH6otiQx62zUki7F3GSdy8mSn2J6C
J2m7KSsK/RQLxUJoIy0D/T27KM0CvYccvtFEGejv2XWxfVr18p2nKWdd8jxNaBIyzniiKVkXwYfg
PE27X2TdFvZYAGzJe0e0i5I8U+O3q2TcAmzxO1AWFsbbQ3hmpd4K1IxzM/UuGtaQhM3zPZFPi8pF
hJ3uhUN3H34FMOkt/oTc4QcZd3iyTyVRhPcAFT67cDfnaxJMb4g8knj06okDbxJ83jTQpNHhvZsO
kZF3Axr7WzJoG4YjkAlvwCOlT+JDZLFBvHwlcbzxiHwy3JaTz4uF5EiKBoNa8C2Kde+WR3Yke0RW
EMFG4nYfPHmDmUgKUfMIK22eeud7HXlfE18j70/QU0MK50FOg5kekgxiA2YYiPflDlJ6sBIs8SQK
NyQKNCpYET1qEWRpQDB2PJ9vQ7DpXb+GI1SOZrDJsJ4n2AKbMHLre5su+5iBBf32Jl7Eaz9eUc4B
2yTym3jd9q6uLvngxTpsKyT7DMk+hiUb9lK2sOFs2qibkcTqvG2JibbA1hG+DwJWBrRBBNiVOWly
8swYj/fLP2y/zJSRp6CPuXftwWSH/ydQTW1sZnyFCExyxCbnG93/TaKwW74X5m7zPDexjp60A7+a
tTdp+9cyJ62SI2mib5IPbDLlbD/KP88Zbb7T/0SxOpqsm+oRvqNIbE6pzZlvU8hRG/4SyJUNZGTb
eAFqsO2PXPLxL5m2/gc8TlrxczoAAA==#>
#endregion

<#
    .NOTES
    --------------------------------------------------------------------------------
     Code generated by:  SAPIEN Technologies, Inc., PowerShell Studio 2018 v5.5.148
     Generated on:       09/08/2021 00:08
     Generated by:       cryos
    --------------------------------------------------------------------------------
    .DESCRIPTION
        GUI script generated by PowerShell Studio 2018
#>


#----------------------------------------------
#region Application Functions
#----------------------------------------------

#endregion Application Functions

#----------------------------------------------
# Generated Form Function
#----------------------------------------------
function Show-CToolbox_GUI_psf {

	#----------------------------------------------
	#region Import the Assemblies
	#----------------------------------------------
	[void][reflection.assembly]::Load('System.Windows.Forms, Version=2.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089')
	[void][reflection.assembly]::Load('System.Design, Version=2.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a')
	[void][reflection.assembly]::Load('System.Drawing, Version=2.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a')
	#endregion Import Assemblies

	#----------------------------------------------
	#region Generated Form Objects
	#----------------------------------------------
	[System.Windows.Forms.Application]::EnableVisualStyles()
	$formCToolbox = New-Object 'System.Windows.Forms.Form'
	$titlelabel = New-Object 'System.Windows.Forms.Label'
	$function4 = New-Object 'System.Windows.Forms.Button'
	$function3 = New-Object 'System.Windows.Forms.Button'
	$function2 = New-Object 'System.Windows.Forms.Button'
	$function1 = New-Object 'System.Windows.Forms.Button'
	$menustrip1 = New-Object 'System.Windows.Forms.MenuStrip'
	$xlsxBrowseFolder = New-Object 'System.Windows.Forms.Button'
	$xlsxboxFolder = New-Object 'System.Windows.Forms.TextBox'
	$labelExportxlsx = New-Object 'System.Windows.Forms.Label'
	$labelExportcsv = New-Object 'System.Windows.Forms.Label'
	$csvBrowseFolder = New-Object 'System.Windows.Forms.Button'
	$csvboxFolder = New-Object 'System.Windows.Forms.TextBox'
	$processtextbox1 = New-Object 'System.Windows.Forms.RichTextBox'
	$imagelistButtonBusyAnimation = New-Object 'System.Windows.Forms.ImageList'
	$timerProcessTracker = New-Object 'System.Windows.Forms.Timer'
	$chiaPlotCheckToolStripMenuItem = New-Object 'System.Windows.Forms.ToolStripMenuItem'
	$backupRestoreToolStripMenuItem = New-Object 'System.Windows.Forms.ToolStripMenuItem'
	$folderbrowserdialog1 = New-Object 'System.Windows.Forms.FolderBrowserDialog'
	$folderbrowserdialog2 = New-Object 'System.Windows.Forms.FolderBrowserDialog'
	$InitialFormWindowState = New-Object 'System.Windows.Forms.FormWindowState'
	#endregion Generated Form Objects

	#----------------------------------------------
	# User Generated Script
	#----------------------------------------------
	
	$formCToolbox_Load = {
		# Hide PowerShell Console
		Add-Type -Name Window -Namespace Console -MemberDefinition '
[DllImport("Kernel32.dll")]
public static extern IntPtr GetConsoleWindow();
[DllImport("user32.dll")]
public static extern bool ShowWindow(IntPtr hWnd, Int32 nCmdShow);
'
		$consolePtr = [Console.Window]::GetConsoleWindow()
		[Console.Window]::ShowWindow($consolePtr, 0)
	}
	
	Add-Type -AssemblyName PresentationCore, PresentationFramework
	function Test-ChiaPlot
	{
		[CmdletBinding()]
		param (
			[Parameter(ValueFromPipelineByPropertyName, ValueFromPipeline)]
			[Alias("FilePath", "FullName", "Filter")]
			[ValidateNotNullOrEmpty()]
			[string[]]$Path,
			[ALias("n")]
			[int]$Challenges = 30
		)
		
		Begin
		{
			$ChiaPath = (Get-Item -Path "$ENV:LOCALAPPDATA\chia-blockchain\app-*\resources\app.asar.unpacked\daemon").FullName
			if ($ENV:Path.Split(";") -notcontains $ChiaPath)
			{
				$ENV:Path += ";$ChiaPath"
			}
			$Proofs = "Proofs ([0-9]*) / ([0-9]*), ([0-9.]*)"
			$Testing = "Testing plot"
			$ErrorString = "ERROR"
		}
		
		Process
		{
			foreach ($plotpath in $Path)
			{
				chia.exe plots check -n $Challenges -g $plotpath 2>&1 | Select-String -SimpleMatch "Proofs", "Error", "Testing" | foreach {
					switch -Regex ($_)
					{
						$Proofs {
							$PlotObject.ProofsFound = $Matches[1] -as [int]
							$PlotObject.Ratio = $Matches[3] -as [double]
							$PlotObject
							break
						}
						$Testing {
							$PlotPath = ($_ -split "Testing plot ")[1].split(' ')[0]
							$Leaf = Split-Path -Path $PlotPath -Leaf
							$KSize = $Leaf -split "plot-k" -split "-" | Select-Object -First 1 -Skip 1
							$PlotId = ($Leaf -split "-" | select -Last 1).Split(".")[0]
							$PlotObject = [PSCustomObject]@{
								PSTypeName   = "PSChiaPlotter.PlotTest"
								Path		 = $PlotPath
								ProofsFound  = 0
								Challenges   = $Challenges
								Ratio	     = 0.0
								KSize	     = $KSize
								PlotId	     = $PlotId
								Errors	     = New-Object System.Collections.Generic.List[string]
							}
							break
						}
						$ErrorString {
							$PlotObject.Errors.Add($_.ToString())
							break
						}
					} #switch
				} #foreach line
			} #foreach
		} #process
	}
	
	function View-Export
	{
		$labelExportcsv.Visible = $true
		$csvBrowseFolder.Visible = $true
		$labelExportxlsx.Visible = $true
		$xlsxBrowseFolder.Visible = $true
		$processtextbox1.Visible = $false
	}
	
	function View-Standard
	{
		$labelExportcsv.Visible = $false
		$csvBrowseFolder.Visible = $false
		$labelExportxlsx.Visible = $false
		$xlsxBrowseFolder.Visible = $false
		$processtextbox1.Visible = $true
	}
	
	$chiaPlotCheckToolStripMenuItem_Click = {
		
		$titlelabel.Text = "Plot Checking"
		
		View-Standard
		
		$function1.Visible = $true
		$function1.Text = "Check Plots"
		$function2.Visible = $true
		$function2.Text = "View"
		$function3.Visible = $true
		$function3.Text = "Export"
		$function4.Visible = $false
		$function4.Text = "Test"
		$processtextbox1.Visible = $true
	}
	
	$backupRestoreToolStripMenuItem_Click = {
		
		$titlelabel.Text = "Backup/Restore"
		
		View-Standard
		
		$function1.Visible = $true
		$function1.Text = "Backup"
		$function2.Visible = $true
		$function2.Text = "Restore"
		$function3.Visible = $true
		$function3.Text = "Schedule"
		$function4.Visible = $true
		$function4.Text = "Delete"
		$processtextbox1.Visible = $true
	}
	
	$function1_Click = {
		
		View-Standard
		
		if ($function1.Text -eq "Check Plots")
		{
			$processtextbox1.Text = "Checking plots may take up to 30s per plot, please be patient whilst this runs in the background"
			$farm = Read-Host -prompt "Please enter your farm path"
			Test-ChiaPlot -Path $farm | Export-Csv -Path .\plotcheck.csv -NoTypeInformation -Append
			
			$processtextbox1.Text = "Installing Excel Module"
			Install-Module importexcel -Scope CurrentUser
			
			$processtextbox1.Text = "Converting .csv to .xlsx"
			Import-CSV .\plotcheck.csv | Export-Excel .\plotcheck.xlsx
			
			$ButtonType = [System.Windows.MessageBoxButton]::Ok
			$MessageIcon = [System.Windows.MessageBoxImage]::Information
			$MessageBody = "The checking process has finished"
			$MessageTitle = "Completed"
			
			[System.Windows.MessageBox]::Show($MessageBody, $MessageTitle, $ButtonType, $MessageIcon)
			
			Remove-Module importexcel
			
			$processtextbox1.Text = "Completed."
			}
		elseif ($function1.Text -eq "Backup")
		{
			$processtextbox1.Text = "Backing up Chia mainnet database in 5 seconds..."
			sleep -Seconds 5
			Copy-Item	"$env:USERPROFILE\.chia\mainnet\db\blockchain_v1_mainnet.sqlite" -Destination "$env:USERPROFILE\.chia\mainnet\db\blockchain_v1_mainnet.sqlite.bak" -PassThru
			$processtextbox1.Text = "Backup complete."
		}
	}
	
	$function2_Click = {
		
		View-Standard
		
		if ($function2.Text -eq "View")
		{
			$rows = Import-Csv -Path .\plotcheck.csv `
					   -Header "Path", "Proofs Found", "Challenges", "Ratio", "KSize", "Plot ID", "Errors" |
			Out-GridView –Title Get-CsvData
		}
		elseif ($function2.Text -eq "Restore")
		{
			$ButtonType = [System.Windows.MessageBoxButton]::OK
			$MessageIcon = [System.Windows.MessageBoxImage]::Warning
			$MessageBody = "!! Shutdown your Chia node before restoring !!"
			$MessageTitle = "Warning"
			
			[System.Windows.MessageBox]::Show($MessageBody, $MessageTitle, $ButtonType, $MessageIcon)
			
			$processtextbox1.Text = "Restoring Chia mainnet database in 5 seconds..."
			sleep -Seconds 5
			Copy-Item	"$env:USERPROFILE\.chia\mainnet\db\blockchain_v1_mainnet.sqlite.bak" -Destination "$env:USERPROFILE\.chia\mainnet\db\blockchain_v1_mainnet.sqlite" -PassThru
			$processtextbox1.Text = "Restore complete."
		}
	}
	
	$function3_Click = {
		
		View-Standard
		
		if ($function3.Text -eq "Export")
		{
			View-Export
		}
		elseif ($function3.Text -eq "Schedule")
		{
			$processtextbox1.Text = "Writing backup script to mainnet folder..."
			sleep -Seconds 1
			Add-Content -Path "$env:USERPROFILE\.chia\mainnet\db\CTBackupScrpt.ps1" -Value 'Copy-Item "$env:USERPROFILE\.chia\mainnet\db\blockchain_v1_mainnet.sqlite" -Destination "$env:USERPROFILE\.chia\mainnet\db\blockchain_v1_mainnet.sqlite.bak"'
			$taskname = "Chia Mainnet Backup"
			$chiamainnetbackup = New-ScheduledTaskAction `
														 -Execute 'powershell.exe' `
														 -Argument -File "$env:USERPROFILE\.chia\mainnet\db\CTBackupScrpt.ps1"
			
			$fob = Read-Host -prompt "Enter desired frequency of backups (Daily, Weekly)"
			
			if ($fob.Text -eq "Daily")
			{
				$time = Read-Host -prompt 'Please enter the time (HH:MM or 9:30PM):'
				$interval = Read-Host -prompt 'Please enter the interval (1=Daily 2=Each other day etc):'
				$tasktrigger = New-ScheduledTaskTrigger -Daily -DaysInterval $interval -At $time
				Register-ScheduledTask $taskname -Action $chiamainnetbackup -Trigger $tasktrigger -Force
			}
			elseif ($fob.Text -eq "Weekly")
			{
				$time = Read-Host -prompt 'Please enter the time (HH:MM or 9:30PM):'
				$day = Read-Host -prompt 'Please enter the day (Mon, Tue, Wed, Thu, Fri, Sat, Sun):'
				$interval = Read-Host -prompt 'Please enter the interval (1=Weekly, 2=Fortnightly, 4=3 Weekly 8=4 Weekly):'
				$tasktrigger = New-ScheduledTaskTrigger -Weekly -WeeksInterval $interval -DaysOfWeek $day -At $time
				Register-ScheduledTask $taskname -Action $chiamainnetbackup -Trigger $tasktrigger -Force
			}
		}
	}
	
	$function4_Click = {
		
		View-Standard
		
		if ($function4.Text -eq "Delete")
		{
	
			$ButtonType = [System.Windows.MessageBoxButton]::YesNo
			$MessageIcon = [System.Windows.MessageBoxImage]::Warning
			$MessageBody = "Delete your mainnet backup. Are you sure?"
			$MessageTitle = "Confirm"
			
			$confirmdelete = [System.Windows.Forms.MessageBox]::Show($MessageBody, $MessageTitle, $ButtonType, $MessageIcon)
			if ($confirmdelete -eq "Yes")
			{
				$processtextbox1.Text = "Deleted mainnet backup."
			}
			else
			{
				$processtextbox1.Text = "Cancelled"
			}
		}
		
	}
	
	
	
	#Export Folder Search
	$csvBrowseFolder_Click={
		if($folderbrowserdialog1.ShowDialog() -eq 'OK')
		{
			$csvboxFolder.Text = $folderbrowserdialog1.SelectedPath
			Copy-Item ".\plotcheck.csv" -Destination $csvboxFolder.Text
		}
	}
	
	$xlsxBrowseFolder_Click={
		if($folderbrowserdialog2.ShowDialog() -eq 'OK')
		{
			$xlsxboxFolder.Text = $folderbrowserdialog2.SelectedPath
			Copy-Item ".\plotcheck.xlsx" -Destination $xlsxboxFolder.Text
		}
	}
	
	
	# --End User Generated Script--
	#----------------------------------------------
	#region Generated Events
	#----------------------------------------------
	
	$Form_StateCorrection_Load=
	{
		#Correct the initial state of the form to prevent the .Net maximized form issue
		$formCToolbox.WindowState = $InitialFormWindowState
	}
	
	$Form_Cleanup_FormClosed=
	{
		#Remove all event handlers from the controls
		try
		{
			$function4.remove_Click($function4_Click)
			$function3.remove_Click($function3_Click)
			$function2.remove_Click($function2_Click)
			$function1.remove_Click($function1_Click)
			$xlsxBrowseFolder.remove_Click($xlsxBrowseFolder_Click)
			$csvBrowseFolder.remove_Click($csvBrowseFolder_Click)
			$formCToolbox.remove_Load($formCToolbox_Load)
			$chiaPlotCheckToolStripMenuItem.remove_Click($chiaPlotCheckToolStripMenuItem_Click)
			$backupRestoreToolStripMenuItem.remove_Click($backupRestoreToolStripMenuItem_Click)
			$formCToolbox.remove_Load($Form_StateCorrection_Load)
			$formCToolbox.remove_FormClosed($Form_Cleanup_FormClosed)
		}
		catch { Out-Null <# Prevent PSScriptAnalyzer warning #> }
	}
	#endregion Generated Events

	#----------------------------------------------
	#region Generated Form Code
	#----------------------------------------------
	$formCToolbox.SuspendLayout()
	$menustrip1.SuspendLayout()
	#
	# formCToolbox
	#
	$formCToolbox.Controls.Add($titlelabel)
	$formCToolbox.Controls.Add($function4)
	$formCToolbox.Controls.Add($function3)
	$formCToolbox.Controls.Add($function2)
	$formCToolbox.Controls.Add($function1)
	$formCToolbox.Controls.Add($menustrip1)
	$formCToolbox.Controls.Add($xlsxBrowseFolder)
	$formCToolbox.Controls.Add($xlsxboxFolder)
	$formCToolbox.Controls.Add($labelExportxlsx)
	$formCToolbox.Controls.Add($labelExportcsv)
	$formCToolbox.Controls.Add($csvBrowseFolder)
	$formCToolbox.Controls.Add($csvboxFolder)
	$formCToolbox.Controls.Add($processtextbox1)
	$formCToolbox.AutoScaleDimensions = '6, 13'
	$formCToolbox.AutoScaleMode = 'Font'
	$formCToolbox.ClientSize = '244, 242'
	$formCToolbox.MainMenuStrip = $menustrip1
	$formCToolbox.MaximizeBox = $False
	$formCToolbox.Name = 'formCToolbox'
	$formCToolbox.Text = 'CToolbox'
	$formCToolbox.add_Load($formCToolbox_Load)
	#
	# titlelabel
	#
	$titlelabel.Anchor = 'Top, Bottom'
	$titlelabel.AutoSize = $True
	$titlelabel.Location = '30, 35'
	$titlelabel.Name = 'titlelabel'
	$titlelabel.Size = '51, 17'
	$titlelabel.TabIndex = 15
	$titlelabel.Text = 'Welcome'
	$titlelabel.TextAlign = 'MiddleCenter'
	$titlelabel.UseCompatibleTextRendering = $True
	#
	# function4
	#
	$function4.Location = '125, 89'
	$function4.Name = 'function4'
	$function4.Size = '90, 23'
	$function4.TabIndex = 9
	$function4.Text = 'function4'
	$function4.UseCompatibleTextRendering = $True
	$function4.UseVisualStyleBackColor = $True
	$function4.Visible = $False
	$function4.add_Click($function4_Click)
	#
	# function3
	#
	$function3.Location = '29, 89'
	$function3.Name = 'function3'
	$function3.Size = '90, 23'
	$function3.TabIndex = 8
	$function3.Text = 'function3'
	$function3.UseCompatibleTextRendering = $True
	$function3.UseVisualStyleBackColor = $True
	$function3.Visible = $False
	$function3.add_Click($function3_Click)
	#
	# function2
	#
	$function2.Location = '125, 60'
	$function2.Name = 'function2'
	$function2.Size = '90, 23'
	$function2.TabIndex = 7
	$function2.Text = 'function2'
	$function2.UseCompatibleTextRendering = $True
	$function2.UseVisualStyleBackColor = $True
	$function2.Visible = $False
	$function2.add_Click($function2_Click)
	#
	# function1
	#
	$function1.Location = '29, 60'
	$function1.Name = 'function1'
	$function1.Size = '90, 23'
	$function1.TabIndex = 6
	$function1.Text = 'function1'
	$function1.UseCompatibleTextRendering = $True
	$function1.UseVisualStyleBackColor = $True
	$function1.Visible = $False
	$function1.add_Click($function1_Click)
	#
	# menustrip1
	#
	[void]$menustrip1.Items.Add($chiaPlotCheckToolStripMenuItem)
	[void]$menustrip1.Items.Add($backupRestoreToolStripMenuItem)
	$menustrip1.Location = '0, 0'
	$menustrip1.Name = 'menustrip1'
	$menustrip1.Size = '244, 24'
	$menustrip1.TabIndex = 1
	$menustrip1.Text = 'menustrip1'
	#
	# xlsxBrowseFolder
	#
	$xlsxBrowseFolder.Location = '70, 204'
	$xlsxBrowseFolder.Name = 'xlsxBrowseFolder'
	$xlsxBrowseFolder.Size = '105, 23'
	$xlsxBrowseFolder.TabIndex = 4
	$xlsxBrowseFolder.Text = 'Browse + Export'
	$xlsxBrowseFolder.UseCompatibleTextRendering = $True
	$xlsxBrowseFolder.UseVisualStyleBackColor = $True
	$xlsxBrowseFolder.Visible = $False
	$xlsxBrowseFolder.add_Click($xlsxBrowseFolder_Click)
	#
	# xlsxboxFolder
	#
	$xlsxboxFolder.AutoCompleteMode = 'SuggestAppend'
	$xlsxboxFolder.AutoCompleteSource = 'FileSystemDirectories'
	$xlsxboxFolder.Location = '59, 210'
	$xlsxboxFolder.Name = 'xlsxboxFolder'
	$xlsxboxFolder.Size = '37, 20'
	$xlsxboxFolder.TabIndex = 3
	$xlsxboxFolder.Visible = $False
	#
	# labelExportxlsx
	#
	$labelExportxlsx.AutoSize = $True
	$labelExportxlsx.Location = '90, 184'
	$labelExportxlsx.Name = 'labelExportxlsx'
	$labelExportxlsx.Size = '63, 17'
	$labelExportxlsx.TabIndex = 13
	$labelExportxlsx.Text = 'Export .xlsx'
	$labelExportxlsx.UseCompatibleTextRendering = $True
	$labelExportxlsx.Visible = $False
	#
	# labelExportcsv
	#
	$labelExportcsv.AutoSize = $True
	$labelExportcsv.Location = '93, 138'
	$labelExportcsv.Name = 'labelExportcsv'
	$labelExportcsv.Size = '60, 17'
	$labelExportcsv.TabIndex = 12
	$labelExportcsv.Text = 'Export .csv'
	$labelExportcsv.UseCompatibleTextRendering = $True
	$labelExportcsv.Visible = $False
	#
	# csvBrowseFolder
	#
	$csvBrowseFolder.Location = '70, 158'
	$csvBrowseFolder.Name = 'csvBrowseFolder'
	$csvBrowseFolder.Size = '105, 23'
	$csvBrowseFolder.TabIndex = 4
	$csvBrowseFolder.Text = 'Browse + Export'
	$csvBrowseFolder.UseCompatibleTextRendering = $True
	$csvBrowseFolder.UseVisualStyleBackColor = $True
	$csvBrowseFolder.Visible = $False
	$csvBrowseFolder.add_Click($csvBrowseFolder_Click)
	#
	# csvboxFolder
	#
	$csvboxFolder.AutoCompleteMode = 'SuggestAppend'
	$csvboxFolder.AutoCompleteSource = 'FileSystemDirectories'
	$csvboxFolder.Location = '14, 210'
	$csvboxFolder.Name = 'csvboxFolder'
	$csvboxFolder.Size = '39, 20'
	$csvboxFolder.TabIndex = 3
	$csvboxFolder.Visible = $False
	#
	# processtextbox1
	#
	$processtextbox1.Location = '29, 124'
	$processtextbox1.Name = 'processtextbox1'
	$processtextbox1.Size = '186, 106'
	$processtextbox1.TabIndex = 14
	$processtextbox1.Text = ''
	$processtextbox1.Visible = $False
	#
	# imagelistButtonBusyAnimation
	#
	$Formatter_binaryFomatter = New-Object System.Runtime.Serialization.Formatters.Binary.BinaryFormatter
	#region Binary Data
	$System_IO_MemoryStream = New-Object System.IO.MemoryStream (,[byte[]][System.Convert]::FromBase64String('
AAEAAAD/////AQAAAAAAAAAMAgAAAFdTeXN0ZW0uV2luZG93cy5Gb3JtcywgVmVyc2lvbj00LjAu
MC4wLCBDdWx0dXJlPW5ldXRyYWwsIFB1YmxpY0tleVRva2VuPWI3N2E1YzU2MTkzNGUwODkFAQAA
ACZTeXN0ZW0uV2luZG93cy5Gb3Jtcy5JbWFnZUxpc3RTdHJlYW1lcgEAAAAERGF0YQcCAgAAAAkD
AAAADwMAAAB2CgAAAk1TRnQBSQFMAgEBCAEAATABAAEwAQABEAEAARABAAT/ASEBAAj/AUIBTQE2
BwABNgMAASgDAAFAAwABMAMAAQEBAAEgBgABMP8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/
AP8AugADwgH/Az4B/wM+Af8DwgH/MAADwgH/A14B/wOCAf8DwgH/sAADPgH/AwAB/wMAAf8DPgH/
MAADggH/Az4B/wM+Af8DXgH/gAADwgH/Az4B/wM+Af8DwgH/IAADPgH/AwAB/wMAAf8DPgH/A8IB
/wNeAf8DggH/A8IB/xAAA8IB/wM+Af8DPgH/A8IB/wNeAf8DPgH/Az4B/wNeAf8EAAOSAf8DkgH/
A8IB/3AAAz4B/wMAAf8DAAH/Az4B/yAAA8IB/wM+Af8DPgH/A8IB/wOCAf8DPgH/Az4B/wOCAf8Q
AAM+Af8DAAH/AwAB/wM+Af8DwgH/A14B/wOCAf8DwgH/A5IB/wOCAf8DggH/A5IB/3AAAz4B/wMA
Af8DAAH/Az4B/zAAA14B/wM+Af8DPgH/A14B/xAAAz4B/wMAAf8DAAH/Az4B/xAAA5IB/wOSAf8D
kgH/A8IB/3AAA8IB/wM+Af8DPgH/A8IB/zAAA8IB/wNeAf8DggH/A8IB/xAAA8IB/wM+Af8DPgH/
A8IB/xAAA8IB/wOSAf8DkgH/A8IB/zgAA8IB/wM+Af8DPgH/A8IB/zAAA8IB/wOCAf8DXgH/A8IB
/zAAA8IB/wPCAf8DkgH/A8IB/zQAA8IB/wPCAf80AAM+Af8DAAH/AwAB/wM+Af8wAANeAf8DPgH/
Az4B/wNeAf8wAAOSAf8DggH/A4IB/wOSAf8wAAPCAf8DwgH/A8IB/wPCAf8wAAM+Af8DAAH/AwAB
/wM+Af8wAAOCAf8DPgH/Az4B/wOCAf8wAAPCAf8DggH/A5IB/wOSAf8wAAPCAf8DwgH/A8IB/wPC
Af8wAAPCAf8DPgH/Az4B/wPCAf8wAAPCAf8DggH/A14B/wPCAf8wAAPCAf8DkgH/A5IB/wPCAf80
AAPCAf8DwgH/EAADwgH/A8IB/xQAA8IB/wOCAf8DXgH/A8IB/zAAA8IB/wOSAf8DkgH/A8IB/zQA
A8IB/wPCAf9UAAPCAf8DwgH/A8IB/wPCAf8QAANeAf8DPgH/Az4B/wNeAf8wAAOSAf8DggH/A5IB
/wOSAf8wAAPCAf8DwgH/A8IB/wPCAf9QAAPCAf8DwgH/A8IB/wPCAf8DwgH/A8IB/wOSAf8DwgH/
A4IB/wM+Af8DPgH/A4IB/yQAA8IB/wPCAf8EAAPCAf8DggH/A5IB/wOSAf8wAAPCAf8DwgH/A8IB
/wPCAf9UAAPCAf8DwgH/BAADkgH/A4IB/wOCAf8DkgH/A8IB/wOCAf8DXgH/A8IB/yAAA8IB/wPC
Af8DwgH/A8IB/wPCAf8DkgH/A5IB/wPCAf80AAPCAf8DwgH/ZAADkgH/A5IB/wOSAf8DkgH/MAAD
wgH/A8IB/wPCAf8DwgH/sAADwgH/A5IB/wOSAf8DwgH/NAADwgH/A8IB/7QAA8IB/wPCAf8DkgH/
A8IB/zQAA8IB/wPCAf+0AAOSAf8DggH/A4IB/wOSAf8wAAPCAf8DwgH/A8IB/wPCAf+gAAPCAf8D
XgH/A4IB/wPCAf8DkgH/A5IB/wOSAf8DwgH/BAADwgH/A8IB/xQAA8IB/wPCAf8DkgH/A8IB/wPC
Af8DwgH/A8IB/wPCAf8kAAPCAf8DwgH/dAADggH/Az4B/wM+Af8DggH/A8IB/wOSAf8DkgH/A8IB
/wPCAf8DwgH/A8IB/wPCAf8QAAOSAf8DggH/A4IB/wOSAf8EAAPCAf8DwgH/JAADwgH/A8IB/wPC
Af8DwgH/cAADXgH/Az4B/wM+Af8DggH/EAADwgH/A8IB/wPCAf8DwgH/EAADkgH/A5IB/wOSAf8D
kgH/MAADwgH/A8IB/wPCAf8DwgH/cAADwgH/A14B/wNeAf8DwgH/FAADwgH/A8IB/xQAA8IB/wOS
Af8DkgH/A8IB/zQAA8IB/wPCAf9sAAPCAf8DPgH/Az4B/wPCAf8wAAPCAf8DXgH/A4IB/wPCAf8w
AAPCAf8DwgH/A5IB/wPCAf80AAPCAf8DwgH/NAADPgH/AwAB/wMAAf8DPgH/MAADggH/Az4B/wM+
Af8DXgH/MAADkgH/A4IB/wOCAf8DkgH/MAADwgH/A8IB/wPCAf8DwgH/MAADPgH/AwAB/wMAAf8D
PgH/MAADXgH/Az4B/wM+Af8DggH/MAADkgH/A5IB/wOSAf8DkgH/MAADwgH/A8IB/wPCAf8DwgH/
MAADwgH/Az4B/wM+Af8DwgH/MAADwgH/A14B/wNeAf8DwgH/MAADwgH/A5IB/wOSAf8DwgH/NAAD
wgH/A8IB/3wAA8IB/wM+Af8DPgH/A8IB/zAAA8IB/wNeAf8DggH/A8IB/zAAA8IB/wPCAf8DkgH/
A8IB/xAAA8IB/wM+Af8DPgH/A8IB/1AAAz4B/wMAAf8DAAH/Az4B/zAAA4IB/wM+Af8DPgH/A14B
/zAAA5IB/wOCAf8DggH/A5IB/xAAAz4B/wMAAf8DAAH/Az4B/1AAAz4B/wMAAf8DAAH/Az4B/zAA
A14B/wM+Af8DPgH/A4IB/wOSAf8DPgH/Az4B/wPCAf8gAAOSAf8DkgH/A5IB/wOSAf8DwgH/A14B
/wOCAf8DwgH/Az4B/wMAAf8DAAH/Az4B/1AAA8IB/wM+Af8DPgH/A8IB/zAAA8IB/wOCAf8DXgH/
A8IB/wM+Af8DAAH/AwAB/wM+Af8gAAPCAf8DkgH/A5IB/wPCAf8DggH/Az4B/wM+Af8DXgH/A8IB
/wM+Af8DPgH/A8IB/6AAAz4B/wMAAf8DAAH/Az4B/zAAA14B/wM+Af8DPgH/A4IB/7AAA8IB/wM+
Af8DPgH/A8IB/zAAA8IB/wOCAf8DXgH/A8IB/xgAAUIBTQE+BwABPgMAASgDAAFAAwABMAMAAQEB
AAEBBQABgAEBFgAD/4EABP8B/AE/AfwBPwT/AfwBPwH8AT8D/wHDAfwBAwHAASMD/wHDAfwBAwHA
AQMD/wHDAf8DwwP/AcMB/wPDAf8B8AH/AfAB/wHwAf8B+QH/AfAB/wHwAf8B8AH/AfAB/wHwAf8B
8AH/AfAB/wHwAf8B8AH/AfAB/wHwAf8B+QHnAcMB/wHDAf8B5wL/AsMB/wHDAf8BwwL/AcABAwH+
AUMB/wHDAv8B5AEDAfwBAwH/AecC/wH8AT8B/AE/BP8B/AE/Af4BfwT/AfwBPwH+AX8E/wH8AT8B
/AE/BP8BwAEnAcABPwHnA/8BwAEDAcIBfwHDA/8DwwH/AcMD/wHDAecBwwH/AecD/wEPAf8BDwH/
AQ8B/wGfAf8BDwH/AQ8B/wEPAf8BDwH/AQ8B/wEPAf8BDwH/AQ8B/wEPAf8BDwH/AQ8B/wGfA/8B
wwH/AcMB/wLDAv8BwwH/AcMB/wLDAv8BwwH/AcABPwHAAQMC/wHDAf8BwAE/AcABAwT/AfwBPwH8
AT8E/wH8AT8B/AE/Cw=='))
	#endregion
	$imagelistButtonBusyAnimation.ImageStream = $Formatter_binaryFomatter.Deserialize($System_IO_MemoryStream)
	$Formatter_binaryFomatter = $null
	$System_IO_MemoryStream = $null
	$imagelistButtonBusyAnimation.TransparentColor = 'Transparent'
	#
	# timerProcessTracker
	#
	#
	# chiaPlotCheckToolStripMenuItem
	#
	$chiaPlotCheckToolStripMenuItem.Name = 'chiaPlotCheckToolStripMenuItem'
	$chiaPlotCheckToolStripMenuItem.Size = '103, 20'
	$chiaPlotCheckToolStripMenuItem.Text = 'Chia Plot Check'
	$chiaPlotCheckToolStripMenuItem.add_Click($chiaPlotCheckToolStripMenuItem_Click)
	#
	# backupRestoreToolStripMenuItem
	#
	$backupRestoreToolStripMenuItem.Name = 'backupRestoreToolStripMenuItem'
	$backupRestoreToolStripMenuItem.Size = '102, 20'
	$backupRestoreToolStripMenuItem.Text = 'Backup/Restore'
	$backupRestoreToolStripMenuItem.add_Click($backupRestoreToolStripMenuItem_Click)
	#
	# folderbrowserdialog1
	#
	#
	# folderbrowserdialog2
	#
	$menustrip1.ResumeLayout()
	$formCToolbox.ResumeLayout()
	#endregion Generated Form Code

	#----------------------------------------------

	#Save the initial state of the form
	$InitialFormWindowState = $formCToolbox.WindowState
	#Init the OnLoad event to correct the initial state of the form
	$formCToolbox.add_Load($Form_StateCorrection_Load)
	#Clean up the control events
	$formCToolbox.add_FormClosed($Form_Cleanup_FormClosed)
	#Show the Form
	return $formCToolbox.ShowDialog()

} #End Function

#Call the form
Show-CToolbox_GUI_psf | Out-Null
